name: dunner
version: git
summary: A Docker based task runner tool
description: |
  Dunner is a task runner tool like Grunt but used Docker images like CircleCI do. | 
  You can define tasks and steps of the tasks in your `.dunner.yaml` file and then run these steps with `Dunner do taskname`
grade: stable
confinement: strict
base: core18

parts:
  dunner:
    plugin: go
    go-importpath: github.com/leopardslab/dunner
    source: .
    source-type: git
    build-packages:
      - gcc

apps:
  dunner:
    command: bin/dunner
